#!/usr/bin/env ruby
$LOAD_PATH << File.expand_path("./lib")

require "tty-command"

require "devinator"

puts Devinator.new

# cmd = TTY::Command.new(uuid: false)
#
# cmd.run "sleep", "4", only_output_on_error: true
